export const data = [
    {
        product_id: "1",
        product_name: "Elegant Cream-Colored Shirt",
        product_image: "Elegant Cream-Colored Shirt.jpeg",
        product_price: "5000",
        product_discount: "10",
        product_discount_price: "270",
        product_sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
        product_brand: "Puma",
        product_brand_logo: "Puma-Logo.jpeg",
    },
    {
        product_id: "2",
        product_name: "Bicolor Crewneck Sweatshirt",
        product_image: "Bicolor Crewneck Sweatshirt.jpeg",
        product_price: "15000",
        product_discount: "50",
        product_discount_price: "100",
        product_sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
        product_brand: "Adidas",
        product_brand_logo: "Adidas-Logo.png",
    },
    {
        product_id: "3",
        product_name: "Ethereal Glide - Airborne Sneaker",
        product_image: "Ethereal Glide - Airborne White Sneaker.jpeg",
        product_price: "25000",
        product_discount: "50",
        product_discount_price: "100",
        product_sizes: ["S", "M", "L", "XL", "XXL",],
        product_brand: "Adidas",
        product_brand_logo: "Adidas-Logo.png",
    },
    {
        product_id: "4",
        product_name: "Minimalist White Baseball Cap",
        product_image: "Minimalist White Baseball Cap.jpeg",
        product_price: "45000",
        product_discount: "50",
        product_discount_price: "100",
        product_sizes: ["S", "M", "L", "XL",],
        product_brand: "Adidas",
        product_brand_logo: "Adidas-Logo.png",
    },
    {
        product_id: "5",
        product_name: "Soothing Knitted Apparel Composition",
        product_image: "Soothing Knitted Apparel Composition.jpeg",
        product_price: "50000",
        product_discount: "50",
        product_discount_price: "100",
        product_sizes: ["S", "M", "L", "XL",],
        product_brand: "Adidas",
        product_brand_logo: "Adidas-Logo.png",
    },
    {
        product_id: "6",
        product_name: "Vintage Crew Neck Sweatshirt",
        product_image: "Vintage Shield Graphic Crew Neck Sweatshirt in Light Grey.jpeg",
        product_price: "100000",
        product_discount: "50",
        product_discount_price: "100",
        product_sizes: ["S", "M", "L", "XL",],
        product_brand: "Adidas",
        product_brand_logo: "Adidas-Logo.png",
    }
]